CovidCares/urls.py
from django.contrib import admin
from django.urls import path, include
import covid_info_pg.urls as covid_info_pg
import vaccine.urls as vaccine_urls
import login.urls as login_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('sign-up/', include('sign_up.urls')),
    path('covid-info/', include(covid_info_pg)),
    path('apotik/', include('apotik_app.urls')),
    path('forum/', include('disc_forum.urls')),
    path('vaccine-info/', include(vaccine_urls)),
    path('accounts/login/', include(login_urls)),
]

apotik_app/urls.py
from django.urls import path
from .views import index, search, search_json

app_name = "apotek"

urlpatterns = [
    path('', index, name = 'index'),
    path('search', search, name = 'search'),
    path('search_json', search_json, name = 'search_json')
    # path('list-apotik', index, name = 'index')
]

covid_info_pg/urls.py
from django.urls import path
from .views import fetch_data_prov, index, get_covid_ind, get_covid_prov

app_name = "covid_info"

urlpatterns = [
    path('', index, name='index'),
    path('api-indonesia/', get_covid_ind, name='covid-ind'),
    path('get-provinsi/', get_covid_prov, name='covid-prov'),
    path('fetch-provinsi/', fetch_data_prov, name='get-prov')
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.login_ajax, name='index'),
    path('login-flutter/', views.loginbyflutter, name='loginApp'),
    path('logout-flutter/', views.logoutbyflutter, name='logoutApp'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    
<head>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body, html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}

		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;
		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}

		.nav_links {
        list-style: none;
      	}

		.nav_links li {
			display: inline-block;
			padding: 0 20px;
			color: black;
		}

		.nav_links li a {
			transition: all 0.2 ease 0s;
		}

		.nav_links li a:hover {
			color : #000000
		}

		.login_btn {
			width: 100%;
			background: #33ccff ;
			color: white ;
		}

        .login_btn:hover {
			box-shadow:  4px 4px 4px 4px rgba(0,0,0,0.2);
			background: #11baf2 ;
		}

		.login_container {
			padding: 0 2rem;
		}

		.input-group-text {
			background: #f7ba5b;
			color: white ;
			border: 0 ;
			border-radius: 0.25rem 0 0 0.25rem;
		}
        
		.input_user, .input_pass:focus {
			box-shadow: none ;
			outline: 0px ;
		}
	</style>

    {% block title %}

    {% endblock title %}

</head>

<body>

    {% include 'navbar.html' %}
    {% block content %}

    {% endblock content %}

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Covid Cares</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'homepage:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/forum">Forums</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Information Page
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'covid_info:index' %}">COVID-19</a></li>
              <li><a class="dropdown-item" href="/vaccine-info">Vaccine</a></li>
              <!-- <li><hr class="dropdown-divider"></li> -->
              <li><a class="dropdown-item" href="{% url 'apotek:index' %}">Nearest Pharmacies and Medicines</a></li>
            </ul>
          </li>
        </ul>
        <!-- <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form> -->
      </div>
    </div>
</nav>